- regExp: ".*\\.ts+$"
  labels: ['typescript']
- regExp: ".*\\.md+$"
  labels: ['documentation']
- regExp: "^(pom\\.xml|package\\.json|build\\.gradle)$"
  labels: ['dependencies']
- regExp: ".*\\.(zip|jar|war|ear)+$"
  labels: ['artifact', 'invalid']
